services:
  ysweet:
    build: .
    container_name: ysweet
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  auth:
    build:
      context: ./backend
      dockerfile: Dockerfile.auth
    container_name: ysweet-auth
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - CONNECTION_STRING=ys://ysweet:8080
    restart: unless-stopped
    depends_on:
      ysweet:
        condition: service_healthy
