FROM node:20-alpine
RUN npm config set registry https://registry.npmmirror.com
WORKDIR /app/backend
COPY package.json package-lock.json* ./
RUN npm install --production
COPY . .
EXPOSE 3001
CMD ["node", "server.js"]
